- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Install the latest version of tools
    ansible.builtin.yum:
      name: "{{ item }}"
      state: present
    loop:
       - php
       - mysql
       - unzip
